# Generated by Django 4.1.6 on 2023-02-21 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
        ('shopper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartinfos',
            name='commodityInfos_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commodity.commodityinfos'),
        ),
    ]
